#!/usr/bin/env bash
# ============================================================
# MarketFlow Worktree Manager
# 병렬 워크트리 생성/관리/삭제 — 포트 자동 할당
#
# Usage:
#   ./scripts/wt.sh create <name>     # 워크트리 생성 + 브랜치
#   ./scripts/wt.sh start  <name>     # Flask + Vite 시작
#   ./scripts/wt.sh stop   <name>     # 서비스 중지
#   ./scripts/wt.sh list              # 활성 워크트리 목록
#   ./scripts/wt.sh remove  <name>    # 워크트리 삭제
#   ./scripts/wt.sh status            # 전체 상태 (포트, PID)
# ============================================================

set -euo pipefail

MAIN_DIR="/c/bitman_marketfloww"
WT_BASE="$MAIN_DIR/.worktrees"
PYTHON="$MAIN_DIR/.venv/Scripts/python.exe"
WT_REGISTRY="$WT_BASE/.registry"

# ── 포트 할당 전략 ──
# Main:  Flask=5001, Vite=4000
# WT 1:  Flask=5011, Vite=4010
# WT 2:  Flask=5021, Vite=4020
# ...
FLASK_BASE=5001
VITE_BASE=4000
PORT_STEP=10

_ensure_dirs() {
    mkdir -p "$WT_BASE" "$WT_REGISTRY"
}

_get_slot() {
    local name="$1"
    # 기존 슬롯이 있으면 반환
    if [ -f "$WT_REGISTRY/$name.slot" ]; then
        cat "$WT_REGISTRY/$name.slot"
        return
    fi
    # 새 슬롯 할당 (1부터 시작, 빈 슬롯 찾기)
    local slot=1
    while true; do
        local taken=0
        for f in "$WT_REGISTRY"/*.slot; do
            [ -f "$f" ] && [ "$(cat "$f")" = "$slot" ] && taken=1 && break
        done
        [ "$taken" = "0" ] && break
        slot=$((slot + 1))
    done
    echo "$slot" > "$WT_REGISTRY/$name.slot"
    echo "$slot"
}

_get_ports() {
    local slot="$1"
    local flask_port=$((FLASK_BASE + slot * PORT_STEP))
    local vite_port=$((VITE_BASE + slot * PORT_STEP))
    echo "$flask_port $vite_port"
}

_wt_dir() {
    echo "$WT_BASE/$1"
}

# ============================================================
# CREATE
# ============================================================
cmd_create() {
    local name="${1:?워크트리 이름을 입력하세요}"
    _ensure_dirs

    local wt_dir
    wt_dir="$(_wt_dir "$name")"

    if [ -d "$wt_dir" ]; then
        echo "[ERROR] 워크트리 '$name' 이미 존재: $wt_dir"
        exit 1
    fi

    local slot
    slot="$(_get_slot "$name")"
    local ports
    ports="$(_get_ports "$slot")"
    local flask_port vite_port
    flask_port=$(echo "$ports" | cut -d' ' -f1)
    vite_port=$(echo "$ports" | cut -d' ' -f2)

    echo "┌─ 워크트리 생성: $name"
    echo "│  경로: $wt_dir"
    echo "│  슬롯: #$slot"
    echo "│  Flask: $flask_port / Vite: $vite_port"
    echo "└─"

    # 브랜치 생성 + 워크트리 추가
    local branch="wt/$name"
    cd "$MAIN_DIR"
    git worktree add "$wt_dir" -b "$branch" 2>/dev/null || \
        git worktree add "$wt_dir" "$branch" 2>/dev/null || \
        git worktree add "$wt_dir" -b "$branch" HEAD

    # 워크트리 전용 .env.worktree 생성 (포트 오버라이드)
    cat > "$wt_dir/.env.worktree" << EOF
# Auto-generated by wt.sh — 워크트리 전용 포트
FLASK_PORT=$flask_port
PORT=$vite_port
WT_NAME=$name
WT_SLOT=$slot
EOF

    # 워크트리 전용 logs 디렉토리
    mkdir -p "$wt_dir/logs"

    # node_modules 심링크 (중복 설치 방지)
    if [ -d "$MAIN_DIR/frontend-react/node_modules" ] && [ ! -e "$wt_dir/frontend-react/node_modules" ]; then
        ln -s "$MAIN_DIR/frontend-react/node_modules" "$wt_dir/frontend-react/node_modules" 2>/dev/null || true
    fi

    # data 디렉토리 심링크 (데이터 공유)
    if [ -d "$MAIN_DIR/data" ] && [ ! -e "$wt_dir/data" ]; then
        rm -rf "$wt_dir/data" 2>/dev/null
        ln -s "$MAIN_DIR/data" "$wt_dir/data" 2>/dev/null || true
    fi

    # us_market/output 심링크
    if [ -d "$MAIN_DIR/us_market/output" ] && [ -d "$wt_dir/us_market" ]; then
        rm -rf "$wt_dir/us_market/output" 2>/dev/null
        ln -s "$MAIN_DIR/us_market/output" "$wt_dir/us_market/output" 2>/dev/null || true
    fi

    # crypto-analytics 심링크
    if [ -d "$MAIN_DIR/crypto-analytics" ] && [ ! -e "$wt_dir/crypto-analytics" ]; then
        rm -rf "$wt_dir/crypto-analytics" 2>/dev/null
        ln -s "$MAIN_DIR/crypto-analytics" "$wt_dir/crypto-analytics" 2>/dev/null || true
    fi

    echo ""
    echo "[OK] 워크트리 '$name' 생성 완료"
    echo "     cd $wt_dir"
    echo "     ./scripts/wt.sh start $name"
}

# ============================================================
# START — Flask + Vite 시작
# ============================================================
cmd_start() {
    local name="${1:?워크트리 이름을 입력하세요}"
    local wt_dir
    wt_dir="$(_wt_dir "$name")"

    if [ ! -f "$wt_dir/.env.worktree" ]; then
        echo "[ERROR] 워크트리 '$name' 없음. 먼저 create 하세요."
        exit 1
    fi

    # 포트 읽기
    source "$wt_dir/.env.worktree"
    local flask_port="$FLASK_PORT"
    local vite_port="$PORT"

    echo "┌─ 서비스 시작: $name"
    echo "│  Flask: $flask_port / Vite: $vite_port"
    echo "└─"

    # Flask 시작
    local flask_running=0
    netstat -ano 2>/dev/null | grep -q ":${flask_port}.*LISTENING" && flask_running=1

    if [ "$flask_running" = "0" ]; then
        echo "[...] Flask 시작 (port $flask_port)..."
        FLASK_PORT=$flask_port PYTHONIOENCODING=utf-8 \
            "$PYTHON" "$wt_dir/flask_app.py" &
        local flask_pid=$!
        echo "$flask_pid" > "$wt_dir/logs/flask.pid"

        # 포트 오픈 대기 (최대 15초)
        for i in $(seq 1 15); do
            sleep 1
            netstat -ano 2>/dev/null | grep -q ":${flask_port}.*LISTENING" && break
        done

        if netstat -ano 2>/dev/null | grep -q ":${flask_port}.*LISTENING"; then
            echo "[OK] Flask 시작 (PID $flask_pid, port $flask_port)"
        else
            echo "[WARN] Flask 시작 대기 중... (PID $flask_pid)"
        fi
    else
        echo "[OK] Flask 이미 실행 중 (port $flask_port)"
    fi

    # Vite 시작 (proxy 대상 포트 동적 설정)
    local vite_running=0
    netstat -ano 2>/dev/null | grep -q ":${vite_port}.*LISTENING" && vite_running=1

    if [ "$vite_running" = "0" ]; then
        echo "[...] Vite 시작 (port $vite_port → Flask $flask_port)..."
        cd "$wt_dir/frontend-react"
        PORT=$vite_port VITE_FLASK_PORT=$flask_port \
            npx vite --port "$vite_port" &
        local vite_pid=$!
        echo "$vite_pid" > "$wt_dir/logs/vite.pid"
        cd "$MAIN_DIR"
        echo "[OK] Vite 시작 (PID $vite_pid, port $vite_port)"
    else
        echo "[OK] Vite 이미 실행 중 (port $vite_port)"
    fi

    echo ""
    echo "  Flask:  http://localhost:$flask_port/api/health"
    echo "  Vite:   http://localhost:$vite_port"
}

# ============================================================
# STOP — 서비스 중지
# ============================================================
cmd_stop() {
    local name="${1:?워크트리 이름을 입력하세요}"
    local wt_dir
    wt_dir="$(_wt_dir "$name")"

    echo "┌─ 서비스 중지: $name"

    # Flask PID
    if [ -f "$wt_dir/logs/flask.pid" ]; then
        local fpid
        fpid=$(cat "$wt_dir/logs/flask.pid")
        taskkill //F //PID "$fpid" 2>/dev/null && echo "│  Flask (PID $fpid) 종료" || echo "│  Flask 이미 종료됨"
        rm -f "$wt_dir/logs/flask.pid"
    fi

    # Vite PID
    if [ -f "$wt_dir/logs/vite.pid" ]; then
        local vpid
        vpid=$(cat "$wt_dir/logs/vite.pid")
        taskkill //F //PID "$vpid" 2>/dev/null && echo "│  Vite (PID $vpid) 종료" || echo "│  Vite 이미 종료됨"
        rm -f "$wt_dir/logs/vite.pid"
    fi

    # 포트 기반 정리 (PID 파일 없을 때 폴백)
    if [ -f "$wt_dir/.env.worktree" ]; then
        source "$wt_dir/.env.worktree"
        for port_pid in $(netstat -ano 2>/dev/null | grep ":${FLASK_PORT}.*LISTENING" | awk '{print $5}' | sort -u); do
            taskkill //F //PID "$port_pid" 2>/dev/null || true
        done
        for port_pid in $(netstat -ano 2>/dev/null | grep ":${PORT}.*LISTENING" | awk '{print $5}' | sort -u); do
            taskkill //F //PID "$port_pid" 2>/dev/null || true
        done
    fi

    echo "└─ 중지 완료"
}

# ============================================================
# LIST — 워크트리 목록
# ============================================================
cmd_list() {
    _ensure_dirs

    echo "┌──────────────────────────────────────────────────────────────"
    printf "│ %-12s %-6s %-8s %-8s %-6s %-6s\n" "NAME" "SLOT" "FLASK" "VITE" "F.PID" "V.PID"
    echo "├──────────────────────────────────────────────────────────────"

    # Main
    local main_flask_pid=""
    for pid in $(netstat -ano 2>/dev/null | grep ":5001.*LISTENING" | awk '{print $5}' | sort -u | head -1); do
        main_flask_pid="$pid"
    done
    printf "│ %-12s %-6s %-8s %-8s %-6s %-6s  ★ MAIN\n" "main" "0" "5001" "4000" "${main_flask_pid:-"-"}" "-"

    # Worktrees
    for slot_file in "$WT_REGISTRY"/*.slot; do
        [ -f "$slot_file" ] || continue
        local wt_name
        wt_name=$(basename "$slot_file" .slot)
        local slot
        slot=$(cat "$slot_file")
        local ports
        ports="$(_get_ports "$slot")"
        local fp vp
        fp=$(echo "$ports" | cut -d' ' -f1)
        vp=$(echo "$ports" | cut -d' ' -f2)

        local wt_dir
        wt_dir="$(_wt_dir "$wt_name")"

        local fpid="-" vpid="-"
        [ -f "$wt_dir/logs/flask.pid" ] && fpid=$(cat "$wt_dir/logs/flask.pid")
        [ -f "$wt_dir/logs/vite.pid" ] && vpid=$(cat "$wt_dir/logs/vite.pid")

        # 서비스 상태 확인
        local f_status="" v_status=""
        netstat -ano 2>/dev/null | grep -q ":${fp}.*LISTENING" && f_status="●" || f_status="○"
        netstat -ano 2>/dev/null | grep -q ":${vp}.*LISTENING" && v_status="●" || v_status="○"

        printf "│ %-12s %-6s %-8s %-8s %-6s %-6s  %s%s\n" \
            "$wt_name" "#$slot" "$fp" "$vp" "$fpid" "$vpid" "$f_status" "$v_status"
    done

    echo "└──────────────────────────────────────────────────────────────"
    echo "  ● = 실행 중  ○ = 중지"
}

# ============================================================
# STATUS — 전체 상태
# ============================================================
cmd_status() {
    cmd_list
    echo ""
    echo "Git worktrees:"
    cd "$MAIN_DIR" && git worktree list
}

# ============================================================
# REMOVE — 워크트리 삭제
# ============================================================
cmd_remove() {
    local name="${1:?워크트리 이름을 입력하세요}"
    local wt_dir
    wt_dir="$(_wt_dir "$name")"

    if [ ! -d "$wt_dir" ]; then
        echo "[ERROR] 워크트리 '$name' 없음"
        # 레지스트리 정리
        rm -f "$WT_REGISTRY/$name.slot"
        exit 1
    fi

    # 서비스 먼저 중지
    cmd_stop "$name" 2>/dev/null || true

    echo "[...] 워크트리 삭제: $name"

    # git worktree remove
    cd "$MAIN_DIR"
    git worktree remove "$wt_dir" --force 2>/dev/null || rm -rf "$wt_dir"

    # 브랜치 삭제
    git branch -D "wt/$name" 2>/dev/null || true

    # 레지스트리 정리
    rm -f "$WT_REGISTRY/$name.slot"

    echo "[OK] 워크트리 '$name' 삭제 완료"
}

# ============================================================
# MAIN
# ============================================================
cmd="${1:-help}"
shift || true

case "$cmd" in
    create)  cmd_create "$@" ;;
    start)   cmd_start "$@" ;;
    stop)    cmd_stop "$@" ;;
    list)    cmd_list ;;
    status)  cmd_status ;;
    remove)  cmd_remove "$@" ;;
    *)
        echo "MarketFlow Worktree Manager"
        echo ""
        echo "Usage:"
        echo "  wt.sh create <name>   워크트리 생성 (포트 자동 할당)"
        echo "  wt.sh start  <name>   Flask + Vite 시작"
        echo "  wt.sh stop   <name>   서비스 중지"
        echo "  wt.sh list            워크트리 목록 + 포트"
        echo "  wt.sh status          전체 상태"
        echo "  wt.sh remove <name>   워크트리 삭제"
        echo ""
        echo "Port allocation:"
        echo "  Main:   Flask=5001, Vite=4000"
        echo "  WT #1:  Flask=5011, Vite=4010"
        echo "  WT #2:  Flask=5021, Vite=4020"
        echo "  WT #N:  Flask=50N1, Vite=40N0"
        ;;
esac
